/*---------------------------------------------------------------------------------------------
 *  Copyright (c) IBAX. All rights reserved.
 *  See LICENSE in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
package updates

var MigrationUpdatePriceCreateExec = `
INSERT INTO "1_platform_parameters" (id, name, value, conditions) VALUES
    (next_id('1_platform_parameters'),'price_create_rate', '1000000', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'),'price_create_exec_@1_new_ecosystem', '100', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'),'price_create_exec_@1_new_table', '1', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'),'price_create_exec_@1_new_column', '1', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'),'price_create_exec_@1_new_contract', '1', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'),'price_create_exec_@1_new_menu', '1', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'),'price_create_exec_@1_new_page', '1', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'),'price_create_exec_@1_new_snippet', '1', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'),'price_create_exec_@1_new_view', '1', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'),'price_create_exec_@1_new_application', '1', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'),'price_create_exec_@1_new_token', '5000', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'),'price_create_exec_@1_new_lang', '1', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'),'price_create_exec_@1_new_section', '1', 'ContractAccess("@1UpdatePlatformParam")');
`

var MigrationUpdatePriceExec = `
INSERT INTO "1_platform_parameters" (id, name, value, conditions) VALUES
	(next_id('1_platform_parameters'), 'price_exec_get_block', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_int', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_get_map_keys', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_pub_to_hex', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_sqrt', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_json_encode_indent', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_encode_base64', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_sorted_keys', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_hex_to_pub', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_throw', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_create_contract', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_edit_language', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_date_time', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_edit_ecosys_name', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_update_notifications', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_update_roles_notifications', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_contract_name', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_bnd_wallet', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_check_signature', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_row_conditions', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_append', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_round', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_lang_res', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_to_upper', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_allow_change_condition', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_bytes_to_string', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_app_param', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_float', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_money', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_del_table', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_string_to_bytes', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_date_time_location', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_h_mac', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_hex_to_bytes', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_split', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_get_column_type', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_unix_date_time_location', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_contract_conditions', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_random', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_get_type', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_del_column', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_update_nodes_ban', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_log10', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_validate_edit_contract_new_value', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_format_money', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_create_language', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_role_access', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_decode_base64', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_unix_date_time', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_get_history', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_floor', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_json_decode', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_update_contract', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_log', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_json_encode', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_to_lower', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_unbnd_wallet', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_get_history_row', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_block_time', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_contract_access', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_transaction_info', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_pow', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_hash', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_check_condition', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_str', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_trim_space', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_address_to_id', '10', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_id_to_address', '10', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_pub_to_id', '10', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_ecosys_param', '10', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_sys_param_string', '10', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_sys_param_int', '10', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_sys_fuel', '10', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_validate_condition', '30', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_eval_condition', '20', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_has_prefix', '10', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_contains', '10', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_replace', '10', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_join', '10', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_update_lang', '10', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_size', '10', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_substr', '10', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_contracts_list', '10', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_is_object', '10', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_compile_contract', '100', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_flush_contract', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_eval', '10', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_len', '5', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_bind_wallet', '10', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_unbind_wallet', '10', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_create_ecosystem', '100', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_table_conditions', '100', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_create_table', '100', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_perm_table', '100', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_column_condition', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_create_column', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_perm_column', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_get_contract_by_name', '20', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_get_contract_by_id', '20', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_money_div', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_check_sign', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_date_format', '50', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_is_honor_node_key', '10', 'ContractAccess("@1UpdatePlatformParam")');
`

var MigrationUpdateAccessExec = `
INSERT INTO "1_platform_parameters" (id, name, value, conditions) VALUES
	(next_id('1_platform_parameters'), 'access_exec_compile_contract', 'ContractAccess("@1NewContract", "@1EditContract", "@1Import")', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'access_exec_update_contract', 'ContractAccess("@1EditContract", "@1Import")', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'access_exec_create_contract', 'ContractAccess("@1NewContract", "@1Import")', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'access_exec_create_table', 'ContractAccess("@1NewTable", "@1NewTableJoint", "@1Import")', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'access_exec_flush_contract', 'ContractAccess("@1NewContract", "@1EditContract", "@1Import")', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'access_exec_perm_table', 'ContractAccess("@1EditTable")', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'access_exec_table_conditions', 'ContractAccess("@1NewTable", "@1Import", "@1NewTableJoint", "@1EditTable")', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'access_exec_column_condition', 'ContractAccess("@1NewColumn", "@1EditColumn")', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'access_exec_create_column', 'ContractAccess("@1NewColumn")', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'access_exec_perm_column', 'ContractAccess("@1EditColumn")', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'access_exec_create_language', 'ContractAccess("@1NewLang", "@1NewLangJoint", "@1Import")', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'access_exec_edit_language', 'ContractAccess("@1EditLang", "@1EditLangJoint", "@1Import")', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'access_exec_create_ecosystem', 'ContractAccess("@1NewEcosystem")', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'access_exec_edit_ecosys_name', 'ContractAccess("@1EditEcosystemName")', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'access_exec_bind_wallet', 'ContractAccess("@1BindWallet")', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'access_exec_unbind_wallet', 'ContractAccess("@1UnbindWallet")', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'access_exec_set_contract_wallet', 'ContractAccess("@1BindWallet", "@1UnbindWallet")', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'access_exec_update_nodes_ban', 'ContractAccess("@1CheckNodesBan")', 'ContractAccess("@1UpdatePlatformParam")'),
    (next_id('1_platform_parameters'), 'access_exec_create_view', 'ContractAccess("@1NewView")', 'ContractAccess("@1UpdatePlatformParam")');
`

var tentative = `
INSERT INTO "1_platform_parameters" (id, name, value, conditions) VALUES
	(next_id('1_platform_parameters'), 'block_reward','10','ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'external_blockchain', '', 'ContractAccess("@1UpdatePlatformParam")'),
	(next_id('1_platform_parameters'), 'price_exec_send_external_transaction', '50', 'ContractAccess("@1UpdatePlatformParam")');
`
