/*---------------------------------------------------------------------------------------------
 *  Copyright (c) IBAX. All rights reserved.
 *  See LICENSE in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
package utils

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockClock is an autogenerated mock type for the Clock type

	return r0
}
