/*---------------------------------------------------------------------------------------------
 *  Copyright (c) IBAX. All rights reserved.
 *  See LICENSE in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

package obs

var systemParametersDataSQL = `
INSERT INTO "1_system_parameters" ("id","name", "value", "conditions") VALUES 
	(next_id('1_system_parameters'),'default_ecosystem_page', 'If(#ecosystem_id# > 1){Include(@1welcome)}', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'default_ecosystem_menu', '', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'default_ecosystem_contract', '', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'gap_between_blocks', '2', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'rollback_blocks', '60', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'honor_nodes', '', 'ContractAccess("@1UpdateSysParam","@1NodeRemoveByKey")'),
	(next_id('1_system_parameters'),'number_of_nodes', '101', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_create_ecosystem', '2000', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_create_table', '25', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_create_column', '25', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_create_contract', '25', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_create_menu', '10', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_create_page', '10', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'max_block_size', '67108864', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'max_tx_size', '33554432', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_ecosys_param', '10', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_sys_param_string', '10', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_sys_param_int', '10', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_sys_fuel', '10', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_validate_condition', '30', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_eval_condition', '20', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_has_prefix', '10', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_contains', '10', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_replace', '10', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_join', '10', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_update_lang', '10', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_size', '10', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_substr', '10', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_contracts_list', '10', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_is_object', '10', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_compile_contract', '100', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_flush_contract', '50', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_eval', '10', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_len', '5', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_bind_wallet', '10', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_unbind_wallet', '10', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_create_ecosystem', '100', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_table_conditions', '100', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_create_table', '100', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_perm_table', '100', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_column_condition', '50', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_create_column', '50', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_perm_column', '50', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_json_to_map', '50', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'max_block_generation_time', '2000', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'block_reward','10','ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'incorrect_blocks_per_day','10','ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'node_ban_time','86400000','ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'node_ban_time_local','1800000','ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_tx_size_wallet', '15', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_create_rate', '1000000', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'test','false','false'),
	(next_id('1_system_parameters'),'price_tx_data', '0', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_contract_by_name', '20', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'price_exec_contract_by_id', '20', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'private_blockchain', '1', 'false'),
	(next_id('1_system_parameters'),'price_create_application', '100', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'external_blockchain', '', 'ContractAccess("@1UpdateSysParam")'),
	(next_id('1_system_parameters'),'pay_free_contract', '@1CallDelayedContract', 'ContractAccess("@1UpdateSysParam")');
`
